jobs:
  prepare_release:
    name: Prepare Release v${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.x
      - name: Install dependencies
        run: pip install https://github.com/praw-dev/praw-release/archive/main.zip
      - name: Prepare Git Variables
        run: |
          git config --global author.email ${{ github.actor }}@users.noreply.github.com
          git config --global author.name ${{ github.actor }}
          git config --global committer.email noreply@github.com
          git config --global committer.name GitHub
      - name: Normalize version and update in code
        run: |
          praw-release bump ${{ github.event.inputs.package }} ${{ github.event.inputs.version }} ${{ github.event.inputs.package }}/${{ github.event.inputs.version_file }} > tmp_version
          echo "version=$(cat tmp_version)" >> $GITHUB_ENV
          rm tmp_version
      - name: Commit changes with desired version
        run: git commit -am "Bump to v${{ env.version }}"
      - name: Update code with next development version
        run: |
          praw-release bump ${{ github.event.repository.name }} unreleased > tmp_version
          echo "dev_version=$(cat tmp_version)" >> $GITHUB_ENV
          rm tmp_version
      - name: Commit changes with development version
        run: git commit -am "Set development version v${{ env.dev_version }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          body: ""
          branch: prepare_release_v${{ env.version }}
          draft: false
          title: Release v${{ env.version }}

name: Prepare Release
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: The version to prepare for release
        required: true
permissions:
  contents: read
  pull-requests: write
