env:
  days-before-close: 30
  days-before-stale: 30
  stale-close-label: Auto-closed - Stale
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-issue-label: ${{ env.stale-close-label }}
          close-issue-message: This issue was closed because it has been stale for ${{ env.days-before-close }} days with no activity.
          close-pr-label: ${{ env.stale-close-label }}
          close-pr-message: This PR was closed because it has been stale for ${{ env.days-before-close }} days with no activity.
          days-before-close: ${{ env.days-before-close }}
          days-before-stale: ${{ env.days-before-stale }}
          exempt-all-assignees: true
          exempt-all-milestones: true
          exempt-draft-pr: true
          exempt-issue-labels: Discussion
          exempt-pr-labels: Discussion
          stale-issue-message: |
            This issue is stale because it has been open for ${{ env.days-before-stale }} days with no activity. 
            
            Remove the Stale label or comment or this will be closed in ${{ env.days-before-close }} days.
          stale-pr-message: |
            This PR is stale because it has been open for ${{ env.days-before-stale }} days with no activity. 
            
            Remove the Stale label or comment or this will be closed in ${{ env.days-before-close }} days.
name: Close stale issues and PRs
on: workflow_call
permissions:
  issues: write
  pull-requests: write
