jobs:
  release_tag:
    if: "startsWith(github.event.head_commit.message, 'Merge pull request #') && contains(github.event.head_commit.message, ' from praw-dev/prepare_release_v')"
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 3
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          cache: pip
          python-version: 3.x
      - name: Install dependencies
        run: pip install https://github.com/praw-dev/praw-release/archive/9a9d3162a6bdfcdfa1bac273734f86ddbfdafe40.zip
      - name: Extract Version
        run: |
          git checkout HEAD^2^
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          git log --format=%B -n 1 | praw-release extract-version > tmp_version
          echo "version=$(cat tmp_version)" >> "$GITHUB_ENV"
          cat tmp_version | python -c 'import sys; from packaging import version; print(int(version.Version(sys.stdin.readline()).is_prerelease))' > tmp_is_prerelease
          echo "is_prerelease=$(cat tmp_is_prerelease)" >> "$GITHUB_ENV"
      - name: Extract Change Log
        run: praw-release changes "$version" > version_changelog
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create GitHub Release
        run: |
          args=(--draft --notes-file version_changelog --target "$commit" --title "v$version")
          if [ "$is_prerelease" = "1" ]; then
            args+=(--prerelease)
          fi
          gh release create "v$version" "${args[@]}"
name: Tag Release
on: workflow_call
permissions:
  contents: write
