jobs:
  release_tag:
    if: "startsWith(github.event.head_commit.message, 'Merge pull request #') && contains(github.event.head_commit.message, ' from praw-dev/prepare_release_v')"
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 3
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          cache: pip
          python-version: 3.x
      - name: Install dependencies
        run: pip install https://github.com/praw-dev/praw-release/archive/9a9d3162a6bdfcdfa1bac273734f86ddbfdafe40.zip
      - name: Extract Version
        run: |
          git checkout HEAD^2^
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_ENV
          git log --format=%B -n 1 | praw-release extract-version > tmp_version
          echo "version=$(cat tmp_version)" >> $GITHUB_ENV
          cat tmp_version | python -c 'import sys; from packaging import version; print(int(version.Version(sys.stdin.readline()).is_prerelease))' > tmp_is_prerelease
          echo "is_prerelease=$(cat tmp_is_prerelease)" >> $GITHUB_ENV
      - name: Extract Change Log
        run: praw-release changes ${{ env.version }} > version_changelog
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create GitHub Release
        run: |
          gh release create "v${{ env.version }}" \
            --draft \
            --notes-file version_changelog \
            --prerelease=${{ env.is_prerelease == '1' }} \
            --target "${{ env.commit }}" \
            --title "v${{ env.version }}"
name: Tag Release
on: workflow_call
permissions:
  contents: write
